version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student123
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net

  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student_db
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: student123
    ports:
      - "8081:8081"
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge
